import { MobDefinition } from '@/types/entities';

export const MOB_DEFINITIONS: MobDefinition[] = [
  // Passive
  { id: 'rabbit', name: 'Rabbit', category: 'passive', stats: { health: 5, maxHealth: 5, attack: 0, defense: 0, speed: 85, attackSpeed: 0 }, alertRange: 60, attackRange: 0, leashDistance: 120, drops: [{ itemId: 'meat', count: 1, chance: 1.0 }], biomes: ['forest'], spawnWeight: 3, color: 0xc0c0c0 },
  { id: 'deer', name: 'Deer', category: 'passive', stats: { health: 10, maxHealth: 10, attack: 0, defense: 1, speed: 95, attackSpeed: 0 }, alertRange: 80, attackRange: 0, leashDistance: 150, drops: [{ itemId: 'meat', count: 2, chance: 1.0 }, { itemId: 'hide', count: 1, chance: 0.5 }, { itemId: 'bone', count: 1, chance: 0.3 }], biomes: ['forest'], spawnWeight: 2, color: 0x8b6914 },
  // Aggressive
  { id: 'slime', name: 'Slime', category: 'aggressive', stats: { health: 20, maxHealth: 20, attack: 5, defense: 1, speed: 60, attackSpeed: 1 }, alertRange: 100, attackRange: 30, leashDistance: 200, drops: [{ itemId: 'slime_gel', count: 1, chance: 0.8 }, { itemId: 'recipe_scroll', count: 1, chance: 0.15 }], biomes: ['forest'], spawnWeight: 2, color: 0x00ff00 },
  { id: 'rock_golem', name: 'Rock Golem', category: 'aggressive', stats: { health: 60, maxHealth: 60, attack: 12, defense: 8, speed: 40, attackSpeed: 0.5 }, alertRange: 80, attackRange: 35, leashDistance: 150, drops: [{ itemId: 'stone', count: 3, chance: 1.0 }, { itemId: 'iron_ore', count: 1, chance: 0.3 }, { itemId: 'recipe_scroll', count: 1, chance: 0.15 }], biomes: ['rocky_highlands'], spawnWeight: 2, color: 0x696969 },
  { id: 'cave_bat', name: 'Cave Bat', category: 'aggressive', stats: { health: 15, maxHealth: 15, attack: 7, defense: 1, speed: 150, attackSpeed: 2 }, alertRange: 120, attackRange: 25, leashDistance: 200, drops: [{ itemId: 'bone', count: 1, chance: 0.5 }], biomes: ['rocky_highlands'], spawnWeight: 3, color: 0x3d3d3d },
  { id: 'poison_frog', name: 'Poison Frog', category: 'aggressive', stats: { health: 12, maxHealth: 12, attack: 8, defense: 2, speed: 90, attackSpeed: 1.5 }, alertRange: 70, attackRange: 25, leashDistance: 150, drops: [{ itemId: 'slime_gel', count: 1, chance: 0.6 }], biomes: ['swamp'], spawnWeight: 3, color: 0x32cd32 },
  { id: 'bog_lurker', name: 'Bog Lurker', category: 'aggressive', stats: { health: 45, maxHealth: 45, attack: 14, defense: 5, speed: 50, attackSpeed: 0.8 }, alertRange: 90, attackRange: 35, leashDistance: 180, drops: [{ itemId: 'rare_mushroom', count: 1, chance: 0.4 }, { itemId: 'swamp_reed', count: 2, chance: 0.7 }, { itemId: 'recipe_scroll', count: 1, chance: 0.15 }], biomes: ['swamp'], spawnWeight: 1, color: 0x556b2f },
  { id: 'fire_elemental', name: 'Fire Elemental', category: 'aggressive', stats: { health: 80, maxHealth: 80, attack: 20, defense: 10, speed: 70, attackSpeed: 1 }, alertRange: 120, attackRange: 40, leashDistance: 200, drops: [{ itemId: 'fire_crystal', count: 1, chance: 0.5 }, { itemId: 'recipe_scroll', count: 1, chance: 0.15 }], biomes: ['volcanic_wastes'], spawnWeight: 2, color: 0xff4500 },
  { id: 'shadow_beast', name: 'Shadow Beast', category: 'aggressive', stats: { health: 100, maxHealth: 100, attack: 25, defense: 12, speed: 100, attackSpeed: 1.5 }, alertRange: 150, attackRange: 35, leashDistance: 300, drops: [{ itemId: 'shadow_essence', count: 1, chance: 0.6 }, { itemId: 'void_crystal', count: 1, chance: 0.2 }, { itemId: 'recipe_scroll', count: 1, chance: 0.15 }], biomes: ['corrupted_lands'], spawnWeight: 2, color: 0x2f0047 },
  { id: 'wisp', name: 'Wisp', category: 'aggressive', stats: { health: 18, maxHealth: 18, attack: 9, defense: 0, speed: 110, attackSpeed: 1.2 }, alertRange: 110, attackRange: 30, leashDistance: 200, drops: [{ itemId: 'rare_mushroom', count: 1, chance: 0.3 }], biomes: ['swamp'], spawnWeight: 2, color: 0x00ffff },
  { id: 'lava_crawler', name: 'Lava Crawler', category: 'aggressive', stats: { health: 55, maxHealth: 55, attack: 16, defense: 7, speed: 65, attackSpeed: 0.9 }, alertRange: 100, attackRange: 35, leashDistance: 180, drops: [{ itemId: 'obsidian', count: 1, chance: 0.4 }, { itemId: 'fire_crystal', count: 1, chance: 0.25 }], biomes: ['volcanic_wastes'], spawnWeight: 2, color: 0xff6600 },
  { id: 'corrupted_npc', name: 'Corrupted NPC', category: 'aggressive', stats: { health: 70, maxHealth: 70, attack: 18, defense: 8, speed: 80, attackSpeed: 1.0 }, alertRange: 130, attackRange: 35, leashDistance: 250, drops: [{ itemId: 'shadow_essence', count: 1, chance: 0.4 }, { itemId: 'corrupted_wood', count: 1, chance: 0.5 }], biomes: ['corrupted_lands'], spawnWeight: 2, color: 0x800080 },
  // Elite
  { id: 'ancient_golem', name: 'Ancient Golem', category: 'elite', stats: { health: 150, maxHealth: 150, attack: 20, defense: 15, speed: 35, attackSpeed: 0.4 }, alertRange: 100, attackRange: 40, leashDistance: 250, drops: [{ itemId: 'iron_ore', count: 5, chance: 1.0 }, { itemId: 'crystal', count: 2, chance: 1.0 }, { itemId: 'recipe_scroll', count: 1, chance: 0.5 }], biomes: ['rocky_highlands'], spawnWeight: 0.1, color: 0xa9a9a9 },
];
